language: ruby

rvm:
  - 2.5.1

sudo: false

env:
  - CI_TEST=core
  - CI_TEST=cli

gemfile:
  - core/Gemfile
  - cli/gemfiles/sass_3_5.gemfile
  - cli/gemfiles/listen_2.gemfile

script: cd $CI_TEST && bundle exec rake

matrix:
  exclude:
  - gemfile: cli/gemfiles/sass_3_5.gemfile
    env: CI_TEST=core
    rvm: 2.5.1
  - gemfile: cli/gemfiles/listen_2.gemfile
    env: CI_TEST=core
    rvm: 2.5.1
  - gemfile: core/Gemfile
    env: CI_TEST=cli
    rvm: 2.5.1
