source 'https://rubygems.org'

# Specify your gem's dependencies in compass-core.gemspec
gemspec

gem 'pry'
gem 'diff-lcs', '~> 1.1.2'
gem 'true', "~> 1.0.0"
gem 'timecop', "~> 0.5.9.2"
gem 'test-unit', '~> 3.0.9'
